export const siteCopy = {
  common: {
    EN: {
      open: "Open",
      viewAll: "View all",
      updated: "Updated",
      comingSoon: "Coming Soon",
      whatsapp: "WhatsApp",
      wiki: "Carloha Wiki",
    },
    CN: {
      open: "打开",
      viewAll: "查看全部",
      updated: "已更新",
      comingSoon: "即将上线",
      whatsapp: "WhatsApp",
      wiki: "Carloha Wiki",
    },
  },
  sidebar: {
    nav: [
      {
        href: "/",
        EN: "Home",
        CN: "首页",
        EN_HINT: "Overview, latest updates, and key shortcuts.",
        CN_HINT: "资料概览、最新更新和关键入口。",
      },
      {
        href: "/vehicles",
        EN: "Vehicle Materials",
        CN: "车型资料",
        EN_HINT: "Brochures, photos, videos, and training assets by vehicle.",
        CN_HINT: "按车型查看手册、图片、视频和培训资料。",
      },
      {
        href: "/general",
        EN: "General Materials",
        CN: "通用资料",
        EN_HINT: "Brand assets, showroom files, campaigns, and dealer guidelines.",
        CN_HINT: "品牌素材、展厅资料、活动物料和经销商指引。",
      },
      {
        href: "/request",
        EN: "Q&A / Request",
        CN: "问题与需求",
        EN_HINT: "Ask questions, report broken links, or request new materials.",
        CN_HINT: "咨询问题、反馈失效链接或申请新资料。",
      },
      {
        href: "/guidelines",
        EN: "Usage Guidelines",
        CN: "使用规范",
        EN_HINT: "Rules for using Carloha materials consistently and safely.",
        CN_HINT: "规范使用 Carloha 资料的基本要求。",
      },
    ],
    navLabel: { EN: "Navigation", CN: "页面导航" },
    howToUseTitle: { EN: "How to Use", CN: "使用说明" },
    howToUseItems: {
      EN: [
        "Use search to find materials by vehicle or category.",
        "Open vehicle cards to access brochures, photos, videos, and training materials.",
        "Files are hosted on Google Drive. Access permission may be required.",
        "Use the request form for new materials or broken links.",
      ],
      CN: [
        "通过搜索框按车型或资料类型查找文件。",
        "打开车型卡片查看手册、图片、视频和培训资料。",
        "资料托管在 Google Drive，部分内容可能需要权限。",
        "如需新资料或发现链接失效，请提交需求表单。",
      ],
    },
  },
  home: {
    heroBody: {
      EN: "One place for vehicle materials, brand assets, and dealer marketing support.",
      CN: "统一管理车型资料、品牌素材和经销商市场支持内容。",
    },
    browseVehicles: { EN: "Browse Vehicle Materials", CN: "浏览车型资料" },
    latestUpdates: { EN: "Latest Updates", CN: "最新更新" },
    vehicleMaterials: { EN: "Vehicle Materials", CN: "车型资料" },
    overviewTitle: { EN: "Overview", CN: "资料概览" },
    popularTitle: { EN: "Popular Materials", CN: "常用资料" },
    readyVehicles: { EN: "Ready vehicles", CN: "可用车型" },
    readyMaterials: { EN: "Ready materials", CN: "可用资料" },
    comingSoon: { EN: "Coming soon", CN: "待上线资料" },
    generalLibraries: { EN: "General libraries", CN: "通用资料库" },
    supportTitle: { EN: "Need something else?", CN: "还缺资料？" },
    supportBody: {
      EN: "Use the request page to report broken links, ask product questions, or request missing materials.",
      CN: "如需反馈失效链接、咨询产品问题或申请缺失资料，可直接前往需求页面。",
    },
    supportAction: { EN: "Open Request Page", CN: "前往需求页面" },
    footer: {
      EN: "© Carloha. For internal sales and dealer marketing support only. Materials are for authorized Carloha sales and dealer use only. Please confirm product information before external communication.",
      CN: "© Carloha。仅供内部销售和经销商市场支持使用。资料仅限授权 Carloha 销售团队和经销商使用，对外沟通前请确认产品信息。",
    },
  },
  vehicles: {
    title: { EN: "Vehicle Materials", CN: "车型资料" },
    intro: {
      EN: "Browse materials by vehicle. Each vehicle page includes specification sheets, brochures, photos, videos, social media videos, and training materials.",
      CN: "按车型查找资料。每个车型页面包含配置表、手册、图片、视频、社媒视频和培训资料。",
    },
    notFound: { EN: "Vehicle not found", CN: "未找到车型" },
    backToList: { EN: "← Back to Vehicle Materials", CN: "← 返回车型资料" },
    imagePlaceholder: { EN: "Vehicle Image", CN: "车型图片" },
    availableMaterials: { EN: "Available Materials", CN: "可用资料" },
    driveNotice: {
      EN: "Files open in Google Drive. Access permission may be required for some materials.",
      CN: "文件将在 Google Drive 中打开，部分资料可能需要访问权限。",
    },
  },
  general: {
    title: { EN: "General Materials", CN: "通用资料" },
    intro: {
      EN: "Access brand assets, event materials, showroom materials, holiday campaigns, PR articles, and dealer guidelines.",
      CN: "访问品牌资产、活动物料、展厅物料、节日活动、PR文章和经销商指南。",
    },
    openFolder: { EN: "Open Folder", CN: "打开文件夹" },
  },
  updates: {
    title: { EN: "Latest Updates", CN: "最新更新" },
    intro: {
      EN: "Latest vehicle material updates based on the Last Updated field.",
      CN: "根据“最后更新”字段展示最新车型资料更新。",
    },
    openVehiclePage: { EN: "Open Vehicle Page", CN: "打开车型页面" },
  },
  requestPage: {
    title: { EN: "Q&A / Request", CN: "问题与需求" },
    intro: {
      EN: "Use this page to request new materials, report broken links, ask product questions, or submit marketing execution questions.",
      CN: "你可以在这里提交新资料需求、反馈失效链接、询问产品资料或市场执行问题。",
    },
    formTitle: { EN: "Marketing Support Request Form", CN: "市场支持需求表" },
    formIntro: {
      EN: "Please use this form to request new marketing materials, report broken links, ask product-related questions, or submit marketing execution questions. The marketing team will review your request and follow up if needed.",
      CN: "请使用此表单提交新市场资料需求、反馈失效链接、询问产品相关问题或提交市场执行问题。市场团队会查看你的需求，并在需要时跟进。",
    },
    contactTitle: { EN: "Contact", CN: "联系方式" },
    email: { EN: "Email:", CN: "邮箱：" },
  },
  guidelines: {
    title: { EN: "Usage Guidelines", CN: "使用规范" },
    intro: {
      EN: "Please follow the guidelines below when using vehicle materials, brand assets, and dealer marketing content.",
      CN: "使用车型资料、品牌素材和经销商市场内容时，请遵守以下规范。",
    },
    rulesTitle: { EN: "General Rules", CN: "通用规则" },
    rules: {
      EN: [
        { lead: "Always use the latest version", tail: " shown on this website." },
        { lead: "Do not modify logos, brand visuals, or official product information", tail: " without approval." },
        { lead: "Confirm product specifications and prices", tail: " before external sharing." },
        { lead: "Dealers may use approved materials", tail: " for local marketing and social media promotion." },
      ],
      CN: [
        { lead: "请始终使用网站上的最新版本", tail: "资料。" },
        { lead: "未经批准，不得修改 Logo、品牌视觉或官方产品信息。", tail: "" },
        { lead: "对外分享前，请确认产品配置和价格信息。", tail: "" },
        { lead: "经销商可以使用已批准资料", tail: "进行本地市场推广和社交媒体宣传。" },
      ],
    },
  },
  faq: {
    title: "FAQ",
    intro: {
      EN: "Quick answers for common marketing hub questions.",
      CN: "常见市场资料问题的快速解答。",
    },
    items: [
      {
        EN: {
          question: "How do I download files?",
          answer: "Open the related Google Drive folder and download the files you need.",
        },
        CN: {
          question: "如何下载文件？",
          answer: "打开对应的 Google Drive 文件夹，下载你需要的资料。",
        },
      },
      {
        EN: {
          question: "What if a link does not open?",
          answer: "Submit the request form and choose “Report broken links”.",
        },
        CN: {
          question: "如果链接打不开怎么办？",
          answer: "请提交需求表，并选择“失效链接反馈”。",
        },
      },
      {
        EN: {
          question: "How often are materials updated?",
          answer: "Materials are expected to be reviewed monthly.",
        },
        CN: {
          question: "资料多久更新一次？",
          answer: "资料预计每月进行一次检查和更新。",
        },
      },
      {
        EN: {
          question: "Can dealers use these materials for social media?",
          answer: "Dealers may use approved materials for local marketing and social media promotion.",
        },
        CN: {
          question: "经销商可以将这些资料用于社交媒体吗？",
          answer: "经销商可以将已批准的资料用于本地市场推广和社交媒体宣传。",
        },
      },
    ],
  },
  searchBox: {
    EN: {
      placeholder: "Search by vehicle or material type...",
      searchLabel: "Keyword",
      results: "Search Results",
      material: "Material",
      noResults: "No matching materials found.",
      open: "Open",
      filterVehicle: "Vehicle / Category",
      filterType: "Material Type",
      filterStatus: "Status",
      allVehicles: "All vehicles / categories",
      allTypes: "All material types",
      allStatuses: "All statuses",
      clearFilters: "Clear filters",
      resultsSummary: "result(s)",
      filtersActive: "Filters active",
    },
    CN: {
      placeholder: "按车型或资料类型搜索...",
      searchLabel: "关键词",
      results: "搜索结果",
      material: "资料",
      noResults: "没有找到匹配的资料。",
      open: "打开",
      filterVehicle: "车型 / 分类",
      filterType: "资料类型",
      filterStatus: "状态",
      allVehicles: "全部车型 / 分类",
      allTypes: "全部资料类型",
      allStatuses: "全部状态",
      clearFilters: "清空筛选",
      resultsSummary: "条结果",
      filtersActive: "已启用筛选",
    },
  },
  requestForm: {
    EN: {
      requestType: "Request Type",
      requestTypes: [
        ["New material request", "New material request"],
        ["Broken link report", "Broken link report"],
        ["Product question", "Product question"],
        ["Marketing execution question", "Marketing execution question"],
        ["Other", "Other"],
      ],
      urgency: "Urgency",
      urgencies: [
        ["Normal", "Normal"],
        ["Urgent", "Urgent"],
        ["Planning ahead", "Planning ahead"],
      ],
      name: "Name",
      email: "Email",
      whatsapp: "WhatsApp",
      market: "Market / Dealer",
      vehicle: "Vehicle",
      vehiclePlaceholder: "e.g. Tiggo 9",
      materialType: "Material Type",
      materialPlaceholder: "e.g. Brochure, video, price list",
      details: "Request Details",
      detailsPlaceholder: "Tell us what you need, where it will be used, and any deadline.",
      submit: "Submit Request",
      submitting: "Submitting...",
      success: "Request submitted. The marketing team will review it soon.",
      submitError: "Unable to submit request.",
      spamTrap: "Leave this field empty",
      vehicleHint: "Choose a vehicle or type a custom model name.",
      materialHint: "Choose a material type or enter your own.",
      requestHelper: "The more detail you give, the faster the team can support you.",
    },
    CN: {
      requestType: "需求类型",
      requestTypes: [
        ["New material request", "新资料需求"],
        ["Broken link report", "失效链接反馈"],
        ["Product question", "产品资料问题"],
        ["Marketing execution question", "市场执行问题"],
        ["Other", "其他"],
      ],
      urgency: "紧急程度",
      urgencies: [
        ["Normal", "普通"],
        ["Urgent", "紧急"],
        ["Planning ahead", "提前规划"],
      ],
      name: "姓名",
      email: "邮箱",
      whatsapp: "WhatsApp",
      market: "市场 / 经销商",
      vehicle: "车型",
      vehiclePlaceholder: "例如：Tiggo 9",
      materialType: "资料类型",
      materialPlaceholder: "例如：手册、视频、价格表",
      details: "需求详情",
      detailsPlaceholder: "请说明你需要什么资料、用途以及截止时间。",
      submit: "提交需求",
      submitting: "提交中...",
      success: "需求已提交，市场团队会尽快查看。",
      submitError: "提交失败，请稍后再试。",
      spamTrap: "请留空",
      vehicleHint: "可选择已有车型，或直接输入自定义车型名称。",
      materialHint: "可选择常见资料类型，或输入自定义资料名称。",
      requestHelper: "描述越具体，市场团队越容易更快支持你。",
    },
  },
  marketingAssistant: {
    EN: {
      launcherSmall: "Ask",
      launcherTitle: "Carloha AI",
      kicker: "Carloha AI",
      title: "Carloha AI",
      close: "Close assistant",
      welcome: "Hi, I am Carloha AI. Ask me about vehicle materials, broken links, or marketing support requests.",
      quickPrompts: [
        "Which Tiggo 9 materials are available?",
        "I need a brochure for Tiggo 9",
        "Where can I find Himla materials?",
        "Where can I find iCAUR V23 videos?",
        "Which materials are available for Tiggo 4?",
        "Where can I find official vehicle photos?",
        "How do I report a broken link?",
        "How can I request new materials?",
        "The Google Drive link does not open",
        "Where can I find dealer guidelines?",
      ],
      thinking: "Thinking...",
      confirm: "Confirm request",
      submit: "Submit Request",
      submitting: "Submitting...",
      missingFields: "Please provide name, email, request type, and details before submitting.",
      placeholder: "Ask Carloha AI...",
      send: "Send",
      fallback: "I could not prepare an answer yet.",
      busy: "Carloha AI is temporarily busy. Please try again later or submit the request form.",
      submitted: "Request submitted. The marketing team will review it soon.",
      submitError: "The request could not be submitted. Please try again later.",
      sources: "Sources",
      sourceLabels: {
        vehicle: "Vehicle Materials",
        general: "General Materials",
        wiki: "Carloha Wiki",
      },
      labels: {
        requestType: "Request Type",
        name: "Name",
        email: "Email",
        whatsapp: "WhatsApp",
        market: "Market / Dealer",
        vehicle: "Vehicle",
        materialType: "Material Type",
        urgency: "Urgency",
        message: "Details",
      },
    },
    CN: {
      launcherSmall: "咨询",
      launcherTitle: "Carloha AI",
      kicker: "Carloha AI",
      title: "Carloha AI",
      close: "关闭助手",
      welcome: "你好，我是 Carloha AI。你可以询问车型资料、失效链接或市场支持需求。",
      quickPrompts: [
        "Tiggo 9 有哪些资料？",
        "我需要 Tiggo 9 的手册",
        "在哪里找 Himla 的资料？",
        "iCAUR V23 的视频在哪里？",
        "Tiggo 4 有哪些资料？",
        "在哪里找官方车型图片？",
        "如何反馈失效链接？",
        "如何申请新资料？",
        "Google Drive 链接打不开怎么办？",
        "经销商指引在哪里？",
      ],
      thinking: "正在思考...",
      confirm: "确认需求",
      submit: "提交需求",
      submitting: "提交中...",
      missingFields: "提交前请补充姓名、邮箱、需求类型和需求详情。",
      placeholder: "询问 Carloha AI...",
      send: "发送",
      fallback: "我暂时还没有整理出答案。",
      busy: "Carloha AI 暂时忙碌，请稍后再试，或直接提交需求表。",
      submitted: "需求已提交，市场团队会尽快查看。",
      submitError: "需求提交失败，请稍后再试。",
      sources: "参考来源",
      sourceLabels: {
        vehicle: "车型资料",
        general: "通用资料",
        wiki: "Carloha Wiki",
      },
      labels: {
        requestType: "需求类型",
        name: "姓名",
        email: "邮箱",
        whatsapp: "WhatsApp",
        market: "市场 / 经销商",
        vehicle: "车型",
        materialType: "资料类型",
        urgency: "紧急程度",
        message: "详情",
      },
    },
  },
};

export function getLocalizedCopy(section, language = "EN") {
  return siteCopy[section]?.[language] || siteCopy[section]?.EN || {};
}
